hmc-cradlepoint/cradlepoint

cradlepoint/components/baseScreen/MenuBar.jsx, cradlepoint/components/baseScreen/PlainScreen.jsx, cradlepoint/components/baseScreen/SplitScreen.css, cradlepoint/components/baseScreen/SplitScreen.jsx, cradlepoint/pages/index.js, cradlepoint/styles/SplitScreen.module.css, cradlepoint/yarn.lock
- Made it so that the `baseScreen/PlainScreen` and `baseScreen/SplitScreen` works now.
- Fixed the menu bar UI
* Styling works differently in NextJS, note convention [name].module.css, and import and usage per `SplitScreen.jsx` example.
UI Update:
=> fix base -> plain screen and split screen templates, fix menu bar

cradlepoint/package-lock.json, cradlepoint/package.json, cradlepoint/yarn.lock
Added react-modal external lib - refer to usage here: https://www.npmjs.com/package/react-modal
=> add react-modal

cradlepoint/components/baseScreen/MenuBar.jsx, cradlepoint/components/baseScreen/PlainScreen.jsx, cradlepoint/components/baseScreen/SplitScreen.css, cradlepoint/components/baseScreen/SplitScreen.jsx, cradlepoint/components/button/CPButton.jsx, cradlepoint/pages/index.js, cradlepoint/styles/SplitScreen.module.css, cradlepoint/yarn.lock
- Added a button component styled to fit the colours we want
- Made some minor spacing changes to the base screen components
Updated UI:
NOTE: Approve the previous PR, `fix-screens...` before approving this one!!
=> Add button component

cradlepoint/components/baseScreen/MenuBar.jsx, cradlepoint/pages/index.js
- Added a table with Edit buttons
Updated UI:
=> add example table with buttons

cradlepoint/package.json, cradlepoint/pages/index.js, cradlepoint/yarn.lock
- Added React Select external lib and component
Updated UI:
Console log of it logging the selected option:
=> add react-select

cradlepoint/components/baseScreen/SplitScreen.jsx, cradlepoint/pages/engagementDetails.jsx, cradlepoint/styles/EngagementDetails.module.css, cradlepoint/styles/SplitScreen.module.css
=> to fix some styling - but temp engagement details

cradlepoint/package-lock.json, cradlepoint/package.json, cradlepoint/pages/api/addNewEngagement.js, cradlepoint/pages/api/getActiveEngagements.js, cradlepoint/schemas/engagementSchema.js, cradlepoint/util/mongodb.js, cradlepoint/yarn.lock
Send a request to addNewEngagement with:
engagementDetails:Test inserting
SE:5236
POC_Engineer:4624
customer:Test Company 4
SFDC:http://www.testlink.com
or make your own 
Notice that the fields for engagementDetails, customer are required to insert, otherwise should return error
Check that engagement is added to the db
=> added ability to add new engagement to db

cradlepoint/package-lock.json, cradlepoint/pages/api/addNewEngagement.js, cradlepoint/pages/api/addNewTestPlan.js, cradlepoint/pages/api/getActiveEngagements.js, cradlepoint/pages/api/getTestPlan.js, cradlepoint/schemas/engagementSchema.js, cradlepoint/schemas/testPlanSchema.js, cradlepoint/util/mongodb.js, cradlepoint/util/newTestPlan.js, cradlepoint/yarn.lock
To test, try to add a new test plan using endpoint addNewTestPlan
In body can try fields 
name:test name
detailedDescription:detailed test
authors:[]
version:1
deviceConfig:[{"system":{"system_id":"BGP Router"}}, []]
customerFeedback:test Feedback
isActive:True
testCases:[]
timeEstimate:1.3
Check that it inserted correctly with a confirmation message
Check that it will not insert incorrect formats
=> Add test plan

cradlepoint/pages/api/getTests.js
use endpoint getTests
can use the testCaseId: 618ff52599912cea5510f06b to test that we can pull them all
=> can get tests based on testCases

cradlepoint/pages/api/getResults.js
use endpoint getResults to test, can use testId: 619007a699912cea5510f098
=> can get results based on specific test

cradlepoint/pages/api/addNewTestCase.js, cradlepoint/schemas/testCaseSchema.js
Can send a post request to the endpoint addNewTestCase with the following test data:
name:test name
description:test
config:[{"system":{"system_id":"BGP Router"}}, []]
BOM:[]
testPlanId:61724e5599915be1b771acb2
tests:[]
timeEstimate:1.3
Make sure that invalid fields will result in an error message
check that the test case was added correctly, and the id was added into the respective testPlan
=> can add new test cases to db

cradlepoint/pages/api/getTestCases.js
same PR as before, but updated with master
=> can pull test cases by testPlan

cradlepoint/components/baseScreen/MenuBar.jsx, cradlepoint/components/fields/DropDown.jsx, cradlepoint/components/fields/Text.jsx, cradlepoint/pages/5TestCaseDetails.jsx, cradlepoint/pages/6TestDetails.jsx, cradlepoint/pages/DeviceLibrary.jsx, cradlepoint/pages/TestCaseLibrary.jsx, cradlepoint/pages/TestPlanLibrary.jsx, cradlepoint/pages/engagementDetails.jsx, cradlepoint/pages/resultModal.jsx, cradlepoint/pages/testCaseInfoModal.jsx, cradlepoint/pages/testInfoModal.jsx, cradlepoint/pages/testPlanInfoModal.jsx, cradlepoint/util/tableColumns.js
- Create test case details UI
- Created test details UI
- Created result modal
- Created all the library pages
=> Test case details UI

cradlepoint/pages/api/getTestCase.js, cradlepoint/pages/api/getTestCasesByPlanId.js, cradlepoint/pages/api/getTestCasesByTestPlan.js
Do not delete branch after merging please!
=> Fixed Broken getTestCase API

cradlepoint/components/tables/Table.jsx, cradlepoint/pages/2home.jsx, cradlepoint/util/tableColumns.js
go to http://localhost:3000/2home and check that the engagements are pulled in correctly
=> Home page integration

cradlepoint/components/tables/Table.jsx, cradlepoint/pages/3EngagementDetails.jsx, cradlepoint/pages/api/getEngagement.js, cradlepoint/pages/api/getTestPlan.js, cradlepoint/pages/api/getTestPlansByEngagementId.js, cradlepoint/pages/engagementDetails.jsx, cradlepoint/util/tableColumns.js
go to the page http://localhost:3000/3EngagementDetails?engagementId=617246a299915be1b771aca0
Check that all data is properly filled into the tables and details sections
=> Get engagement

cradlepoint/pages/5TestCaseDetails.jsx, cradlepoint/pages/api/getTestCase.js, cradlepoint/util/tableColumns.js
send request to http://localhost:3000/api/getTestCase?_id=618ff52599912cea5510f06b to check that the endpoint correctly pulls in the BOM with the test case. 
Visit http://localhost:3000/5TestCaseDetails?testCaseId=618ff52599912cea5510f06b and check that the data is pulled in as expected
=> Test case details integration

cradlepoint/pages/6TestDetails.jsx, cradlepoint/pages/api/getResults.js, cradlepoint/pages/api/getTest.js, cradlepoint/util/tableColumns.js
Check that all details show fine & compiles without error at http://localhost:3000/6TestDetails?_id=619007a699912cea5510f098
To test getTest API: http://localhost:3000/api/getTest?_id=619007a699912cea5510f098
=> Integrate test details

cradlepoint/pages/api/getLibraryTestCases.js
Test it pulls the library test cases from db. Test with endpoint http://localhost:3000/api/getLibraryTestCases
=> added endpoint to get library test cases

cradlepoint/pages/DeviceLibrary.jsx, cradlepoint/pages/TestCaseLibrary.jsx, cradlepoint/pages/TestPlanLibrary.jsx, cradlepoint/pages/api/getAllDevices.js, cradlepoint/pages/api/getArchivedTestPlans.js, cradlepoint/util/tableColumns.js
Integrated the library endpoints (getLibraryTestCases, getLibraryTestPlan, getAllDevices)
Made tables all default hide id
=> Integration libraries

cradlepoint/pages/2home.jsx, cradlepoint/pages/3EngagementDetails.jsx, cradlepoint/pages/4TestPlanDetails.jsx, cradlepoint/pages/5TestCaseDetails.jsx, cradlepoint/pages/TestCaseLibrary.jsx, cradlepoint/pages/TestPlanLibrary.jsx, cradlepoint/pages/api/addNewEngagement.js, cradlepoint/pages/createNewModalFlow/createNewModalFlow.jsx, cradlepoint/pages/deviceModals/selectDevice.jsx
For engagement, test plan, test case details
TODO: getLibraryTests endpoint is not implemented yet
=> Integrated create new modal flows

cradlepoint/pages/api/getAllDevices.js, cradlepoint/pages/api/getArchivedTestPlans.js
Pulls all devices from the db, use the endpoint http://localhost:3000/api/getAllDevices to test that it pulls all devices
=> added endpoint to get all devices

cradlepoint/pages/api/editEngagement.js, cradlepoint/pages/api/editResult.js, cradlepoint/pages/api/editTest.js, cradlepoint/pages/api/editTestCase.js, cradlepoint/pages/api/editTestPlan.js, cradlepoint/schemas/engagementSchema.js, cradlepoint/schemas/testCaseSchema.js, cradlepoint/schemas/testPlanSchema.js, cradlepoint/schemas/testSchema.js
Does not move into utils yet, will do that in another pull request.
=> Refactor edit endpoints

cradlepoint/pages/api/addNewTest.js, cradlepoint/util/addEntry.js
Can add tests to the db. Can use the following information to test
testCaseId:618ff52599912cea5510f
name:TEST
details:TEST DETAIL
results:[]
=> fixed add test endpoint

cradlepoint/pages/api/addNewTestCase.js, cradlepoint/schemas/testCaseSchema.js, cradlepoint/util/addEntry.js
fixed adding new test case to db. To test, can use the following input in the endpoint: http://localhost:3000/api/addNewTestCase
{
"timeEstimate": 1.3,
"description": "test",
"config": "config.",
"name": "Test Case 1234",
"tests": [
"61b69c69775744d2ff528def"
],
"BOM": [
{
"isOptional": true,
"quantity": 12,
"deviceId": "617251a399915be1b771acb6"
}
],
"testPlanId": "6172500699915be1b771acb3"
}
=> Fix add test case

cradlepoint/pages/api/addNewTestPlan.js, cradlepoint/schemas/testPlanSchema.js, cradlepoint/util/addEntry.js
can send to http://localhost:3000/api/addNewTestPlan with following data to test
{
"name": "LTE Failover",
"detailedDescription": "test description",
"version": "1234",
"deviceConfig": "[{'system':{'system_id':'LTE Router'}}, []]",
"customerFeedback": "Works as expected",
"testCases": ["619003fec01efe48e4b3fe0d"],
"authors": [""],
"isActive": false,
"engagementId": "617246a299915be1b771aca0",
"summaryBOM": [
{
"isOptional": true,
"quantity": 12,
"deviceId": "617251a399915be1b771acb6"
}
]
}
=> updated testPlan schema and add endpoint

cradlepoint/pages/api/addNewEngagement.js, cradlepoint/schemas/engagementSchema.js, cradlepoint/util/addEntry.js
To test go to endpoint http://localhost:3000/api/addNewEngagement and send:
{
"name":"Engagement 2",
"statusCode": 2,
"engagementDetails": "Test Details 2",
"SE": "1234",
"POC_Engineer": "2345",
"customer": "Small Finance",
"SFDC": "https://cradlepoint.lightning.force.com/lightning/r/Opportunity/006380...",
"testPlanId": "61724e5599915be1b771acb2",
"createdOn": "2021-11-20T15:00:00.000Z"
}
=> fixed add engagement endpoint

cradlepoint/pages/DeviceLibrary.jsx, cradlepoint/pages/DeviceModalForm.jsx, cradlepoint/pages/api/addNewDevice.js, cradlepoint/schemas/deviceSchema.js, cradlepoint/util/tableColumns.js
Check that devices are able to be added correctly. Can test at endpoint http://localhost:3000/api/addNewDevice, with the body of:
{
"deviceName": "testName",
"codeVersion": "1.1.1",
"SKU": "testSKU.",
"deviceType": "software"
}
Also check that you can see and add new devices from the library page correctly
=> Device library

cradlepoint/pages/3EngagementDetails.jsx, cradlepoint/pages/4TestPlanDetails.jsx, cradlepoint/pages/5TestCaseDetails.jsx, cradlepoint/pages/6TestDetails.jsx, cradlepoint/pages/ModalForms/EngagementModalForm.jsx, cradlepoint/pages/ModalForms/TestModalForm.jsx, cradlepoint/pages/ModalForms/TestPlanModalForm.jsx, cradlepoint/schemas/engagementSchema.js, cradlepoint/schemas/resultSchema.js, cradlepoint/schemas/testCaseSchema.js, cradlepoint/schemas/testPlanSchema.js, cradlepoint/schemas/testSchema.js, cradlepoint/util/tableColumns.js
- updated name in BigTextInput for EngagementModalForm and TestPlanModalForm
=> Rename re factor db 

cradlepoint/pages/3EngagementDetails.jsx, cradlepoint/pages/4TestPlanDetails.jsx, cradlepoint/pages/5TestCaseDetails.jsx, cradlepoint/pages/6TestDetails.jsx, cradlepoint/pages/ModalForms/EngagementModalForm.jsx, cradlepoint/pages/ModalForms/TestModalForm.jsx, cradlepoint/pages/ModalForms/TestPlanModalForm.jsx, cradlepoint/schemas/engagementSchema.js, cradlepoint/schemas/resultSchema.js, cradlepoint/schemas/testCaseSchema.js, cradlepoint/schemas/testPlanSchema.js, cradlepoint/schemas/testSchema.js, cradlepoint/util/tableColumns.js
Provides all the fixes for the DB renames I've done.
=> Re name re factor db

cradlepoint/pages/2home.jsx, cradlepoint/pages/5TestCaseDetails.jsx, cradlepoint/pages/7ResultDetails.jsx, cradlepoint/pages/DeviceModalForm.jsx, cradlepoint/pages/ModalForms/EngagementModalForm.jsx, cradlepoint/pages/ModalForms/TestModalForm.jsx, cradlepoint/pages/ResultModalForm.jsx, cradlepoint/pages/createNewModalFlow.jsx, cradlepoint/schemas/testSchema.js, cradlepoint/util/addEntry.js, cradlepoint/util/tableColumns.js
- fixed addTest query
- updated subject to name in test modal form
- after submitting the query, will exit modal and refresh testCaseDetails page automatically
=> Add new test from scratch

cradlepoint/components/baseScreen/SplitScreen.jsx, cradlepoint/components/fields/DropDown.jsx, cradlepoint/pages/3EngagementDetails.jsx, cradlepoint/pages/DeviceModalForm.jsx, cradlepoint/pages/ModalForms/EngagementModalForm.jsx, cradlepoint/pages/ModalForms/TestPlanModalForm.jsx, cradlepoint/pages/ResultModalForm.jsx
Issues that are fixed:
- engagementModalForm will reset data after **Back** then reopened
- Made all text in all of the details page have word wrap (next line automatically)
- made SFDC link to clickable hyperlink
- made dropdown component functional and updated some input fields to dropdown 
-  resultStatus in resultModalForm (Pass, Unknown, Fail)
- isActive in testPlanModalForm (true, false)
- deviceType in deviceModalForm (Hardware, Software)
=> Fixes to some of the issues

pages/ResultModalForm.jsx
=> missed a case

next.config.js, package-lock.json, package.json, pages/2home.jsx, pages/3EngagementDetails.jsx, pages/4TestPlanDetails.jsx, pages/5TestCaseDetails.jsx, pages/6TestDetails.jsx, pages/7ResultDetails.jsx, pages/DeviceLibrary.jsx, pages/TestCaseLibrary.jsx, pages/TestLibrary.jsx, pages/TestPlanLibrary.jsx, pages/api/getActiveEngagements.js, pages/api/getAllDevices.js, pages/api/getEngagement.js, pages/api/getLibraryTestCases.js, pages/api/getLibraryTestPlans.js, pages/api/getLibraryTests.js, pages/api/getResult.js, pages/api/getResults.js, pages/api/getTest.js, pages/api/getTestCase.js, pages/api/getTestCasesByTestPlan.js, pages/api/getTestPlan.js, pages/api/getTestPlansByEngagementId.js, pages/api/getTests.js, yarn.lock
https://refactorapi.d33prfbtsjth2k.amplifyapp.com/
Follow that link and click through the website making sure that things work the way we think they should. Everything should be working, I think including adding
=> Refactor api to use with AWS

pages/2home.jsx, pages/3EngagementDetails.jsx, pages/api/deleteEngagement.js, pages/api/deleteResult.js, pages/api/deleteTest.js, pages/api/deleteTestCase.js, pages/api/deleteTestCaseBOM.js, pages/api/deleteTestPlan.js, util/deleteEntry.js
Finished implementation + tested up till engagement level. Code implemented but not tested at engagement level (i.e. deleting an engagement) because blocked by Matt working on backend. Receiving error 500 when trying to create a new engagement.
=> Continued delete implementation

pages/2home.jsx, pages/3EngagementDetails.jsx, pages/4TestPlanDetails.jsx, pages/5TestCaseDetails.jsx, pages/6TestDetails.jsx, pages/ModalForms/DeleteModalForm.jsx
made a warning modal for deletes
*important: once the new modal UI is merged, be sure to update this code too
=> Warning modal for deletes

pages/DeviceModalForm.jsx, pages/ModalForms/EngagementModalForm.jsx, pages/ModalForms/TestCaseModalForm.jsx, pages/ModalForms/TestModalForm.jsx, pages/ModalForms/TestPlanModalForm.jsx, pages/ResultModalForm.jsx, pages/createNewModalFlow.jsx, pages/deviceModals/selectDevice.jsx, pages/deviceModals/selectQuantity.jsx, styles/Modal.module.css, yarn.lock
- Added scrolling ability to modals
- Added a light border to modals
- Edit aesthetics of modals so buttons are row aligned vs. column aligned
Re: scrolling, as seen above, the scroll feature is still not completely great. When trying to scroll back up, the max. scroll ability is the above. It doesn't go all the way up. That being said, you can adjust the text box size so that you can scroll completely back up as needed. The most important fix I think is that we can scroll down so that the button functionality is not clipped off.
Solution found via: https://github.com/reactjs/react-modal/issues/283 doesn't seem to be a better way to handle scrolling at the moment.
=> Allow for scrolling on modals
